name        = input('Escreva seu nome: ')
cpf         = input('Escreva seu cpf: ')
endereco    = input('Escreva seu endereço: ')
idade       = input('Escreva sua idade: ')
altura      = input('Escreva sua altura')
telefone    = input('Escreva seu telefone')
